language: python
python:
  - 3.6

services:
  - docker

install:
  - docker build -t max-image-segmenter .
  - docker run -it -d -p 5000:5000 max-image-segmenter
  - pip install pytest requests flake8
  - flake8 . --max-line-length=127

before_script:
  - sleep 10

script:
  - pytest tests/test.py
