name: Docker Image CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
          python-version: 3.6

    - name: Build the Docker image
      run: docker build -t max-image-segmenter .

    - name: Run the Docker image
      run: docker run -it --rm -d -p 5000:5000 max-image-segmenter

    - name: Install dependencies
      run: pip install pytest requests flake8

    - name: Lint with flake8
      run: flake8 . --max-line-length=127

    - name: Wait for container to get ready
      run: sleep 30

    - name: Test with pytest
      run: pytest tests/test.py
name: "Issue assigner"

on: [issues, issue_comment]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: estrada9166/issue-assigner@v1
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        WITH_COMMENTS: true
